### PR TITLE
Add support for wayland session and use deviceinfo

### PR DESCRIPTION
**Pull request by mariogrip**
This allows the support for wayland session by splitting mir and wayland into two different packages. ubuntu-touch-session-mir is currently default.

### CODE REVIEW

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
Please ensure all filed have a trailing newline. Also mark any PRs that must be merged before this.

**Comment by mariogrip** [comment]
> Please ensure all filed have a trailing newline. Also mark any PRs that must be merged before this.

Added trailing newline, and pr: https://gitlab.com/ubports/core/seeds/ubuntu-touch/merge_requests/7/diffs should work without the pr as we specify mir first, but to be sure we add it to the meta packages.

**Comment by UniversalSuperBox** [comment]
device-info isn't currently installed on the devel images, is it in edge yet?

**Comment by mariogrip** [comment]
> device-info isn't currently installed on the devel images, is it in edge yet?

Yes it's in edge

**Comment by mariogrip** [comment]
I can split this up so we get it into xenial without device-info

**Comment by mariogrip** [comment]
I have spitted this up now,
https://github.com/ubports/ubuntu-touch-session/pull/11
https://github.com/ubports/ubuntu-touch-session/pull/12

**Pull request closed without merging**
